name: login_ui
version: 1.0.0+1
publish_to: none
description: Login UI
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  get: 4.6.5
  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

