name: book_bank
version: 1.0.0+1
publish_to: none
description: Book Bank
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  advance_pdf_viewer: ^2.0.1
  syncfusion_flutter_pdfviewer: ^20.3.58
  velocity_x: ^3.6.0
  logger: ^1.1.0
  image_picker: ^0.8.6
  file_picker: ^5.2.4
  firebase_storage: ^11.0.7


dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

